name: Publish project to Maven repository
# Publish manually
# OR, publish per each commit
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Spigot-BuildTools
        run: |
          mkdir -p .spigot-buildtools
          cd .spigot-buildtools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          java -jar BuildTools.jar --rev 1.21 --remapped
          java -jar BuildTools.jar --rev 1.20.4 --remapped
          java -jar BuildTools.jar --rev 1.20.5 --remapped
          java -jar BuildTools.jar --rev 1.20.6 --remapped
          cd ..
          rm -R .spigot-buildtools
        env:
          SPIGOT_M2: ~/.m2/repository/org/spigotmc/spigot

      - name: Publish with Gradle
        run: ./gradlew shadowJar publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)
