name: Publish project to Maven repository
# Publish manually
# OR, publish per each commit
on:
  push:
    branches: [ master ]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "1.21", "1.20.4", "1.20.5", "1.20.6" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: "Cache: Maven-Repository"
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Spigot-BuildTools
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p .spigot-buildtools
          cd .spigot-buildtools
          wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar -O BuildTools.jar
          java -jar BuildTools.jar --rev ${{ matrix.version }} --remapped
          cd ..
          rm -R .spigot-buildtools

      - name: Check directory contents
        run: ls -la ~/.m2/repository/org/spigotmc/spigot/1.21-R0.1-SNAPSHOT/

      - name: Publish with Gradle
        run: ./gradlew shadowJar publish
        env:
          MAVEN_NAME: ${{ secrets.MAVEN_NAME }} # token name
          MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }} # token secret (password)